// Generated by build_data.py — do not edit by hand.
window.DONATIONS = [
 {
  "date": "2026-01-21",
  "amount": 1000.0,
  "name": "Carlos Alberto Migoya (Jackson Health System)",
  "city": "Miami",
  "industry": "Hospital executive",
  "group": "health",
  "donorKey": "carlos alberto migoya (jackson health system)"
 },
 {
  "date": "2026-01-27",
  "amount": 5000.0,
  "name": "Henry Torres (Astor Companies)",
  "city": "Coral Gables",
  "industry": "Real estate developer",
  "group": "re",
  "donorKey": "henry torres (astor companies)"
 },
 {
  "date": "2026-01-27",
  "amount": 2000.0,
  "name": "Carlos Lago (Greenberg Traurig)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "carlos lago (greenberg traurig)"
 },
 {
  "date": "2026-01-27",
  "amount": 500.0,
  "name": "Maria Molina",
  "city": "Coral Gables",
  "industry": "Engineer",
  "group": "build",
  "donorKey": "maria molina"
 },
 {
  "date": "2026-01-27",
  "amount": 500.0,
  "name": "Maria Palacio",
  "city": "Coral Gables",
  "industry": "Real estate agent",
  "group": "re",
  "donorKey": "maria palacio"
 },
 {
  "date": "2026-01-27",
  "amount": 500.0,
  "name": "Eduardo Suarez",
  "city": "Miami",
  "industry": "Surveyor",
  "group": "build",
  "donorKey": "eduardo suarez"
 },
 {
  "date": "2026-01-27",
  "amount": 400.0,
  "name": "Victoria Mendez (former city of Miami attorney)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "victoria mendez (former city of miami attorney)"
 },
 {
  "date": "2026-01-28",
  "amount": 5000.0,
  "name": "CTS Engineering Inc.",
  "city": "Doral",
  "industry": "Engineering",
  "group": "build",
  "donorKey": "cts engineering inc"
 },
 {
  "date": "2026-02-04",
  "amount": 4000.0,
  "name": "Coralee Penabad",
  "city": "Miami",
  "industry": "Developer",
  "group": "re",
  "donorKey": "coralee penabad"
 },
 {
  "date": "2026-02-05",
  "amount": 5000.0,
  "name": "Weiss Serota Helfman Cole & Bierman",
  "city": "Coral Gables",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "weiss serota helfman cole & bierman"
 },
 {
  "date": "2026-02-05",
  "amount": 1000.0,
  "name": "Abreu Homes Inc.",
  "city": "Miami Lakes",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "abreu homes inc"
 },
 {
  "date": "2026-02-09",
  "amount": 12500.0,
  "name": "PRH Investments LLC (Related Group)",
  "city": "Miami",
  "industry": "Investments company",
  "group": "re",
  "donorKey": "prh investments llc (related group)"
 },
 {
  "date": "2026-02-09",
  "amount": 7500.0,
  "name": "Ponce Park Residences, LLC (Allen Morris)",
  "city": "Coral Gables",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "ponce park residences llc (allen morris)"
 },
 {
  "date": "2026-02-09",
  "amount": 7500.0,
  "name": "3101 Grove Trustee, LLC (Allen Morris)",
  "city": "Coral Gables",
  "industry": "Trustee/holding company",
  "group": "re",
  "donorKey": "3101 grove trustee llc (allen morris)"
 },
 {
  "date": "2026-02-09",
  "amount": 6250.0,
  "name": "RUDG LLC (Related Group)",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "rudg llc (related group)"
 },
 {
  "date": "2026-02-09",
  "amount": 6250.0,
  "name": "Related Urban Construction LLC",
  "city": "Miami",
  "industry": "Construction company",
  "group": "build",
  "donorKey": "related urban construction llc"
 },
 {
  "date": "2026-02-09",
  "amount": 5000.0,
  "name": "R. G. Business, Inc.",
  "city": "Miami",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "r g business inc"
 },
 {
  "date": "2026-02-09",
  "amount": 5000.0,
  "name": "School Development HC Finance",
  "city": "Miami",
  "industry": "School developers",
  "group": "misc",
  "donorKey": "school development hc finance"
 },
 {
  "date": "2026-02-09",
  "amount": 5000.0,
  "name": "Coastland Construction Inc.",
  "city": "Miami",
  "industry": "Construction company",
  "group": "build",
  "donorKey": "coastland construction inc"
 },
 {
  "date": "2026-02-09",
  "amount": 5000.0,
  "name": "Coastland Construction Management",
  "city": "Miami",
  "industry": "Construction company",
  "group": "build",
  "donorKey": "coastland construction management"
 },
 {
  "date": "2026-02-09",
  "amount": 1500.0,
  "name": "SMGQ Law",
  "city": "Coral Gables",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "smgq law"
 },
 {
  "date": "2026-02-11",
  "amount": 5000.0,
  "name": "Daniel Berkowitz",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "daniel berkowitz"
 },
 {
  "date": "2026-02-12",
  "amount": 5000.0,
  "name": "Elite Decor Inc.",
  "city": "Miami",
  "industry": "Remodeling",
  "group": "build",
  "donorKey": "elite decor inc"
 },
 {
  "date": "2026-02-12",
  "amount": 5000.0,
  "name": "Vertical Specialist Inc.",
  "city": "Miami",
  "industry": "Window treatments",
  "group": "build",
  "donorKey": "vertical specialist inc"
 },
 {
  "date": "2026-02-13",
  "amount": 2585.82,
  "name": "Willy Bermello",
  "city": "Coral Gables",
  "industry": "Architect",
  "group": "build",
  "donorKey": "willy bermello"
 },
 {
  "date": "2026-02-17",
  "amount": 5000.0,
  "name": "Laborcon, LLC (Coastal Construction)",
  "city": "Miami",
  "industry": "Construction",
  "group": "build",
  "donorKey": "laborcon llc (coastal construction)"
 },
 {
  "date": "2026-02-20",
  "amount": 5000.0,
  "name": "Kendall Associates I, LLLP",
  "city": "Sunrise",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "kendall associates i lllp"
 },
 {
  "date": "2026-02-26",
  "amount": 5000.0,
  "name": "Bailey Raposa (Terra)",
  "city": "Coconut Grove",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "bailey raposa (terra)"
 },
 {
  "date": "2026-03-09",
  "amount": 10000.0,
  "name": "SG Manager LLC (Michael Swerdlow)",
  "city": "Coconut Grove",
  "industry": "Property management",
  "group": "re",
  "donorKey": "sg manager llc (michael swerdlow)"
 },
 {
  "date": "2026-03-09",
  "amount": 10000.0,
  "name": "Midtown Development LLC",
  "city": "Miami",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "midtown development llc"
 },
 {
  "date": "2026-03-09",
  "amount": 10000.0,
  "name": "Boich Companies, LLC",
  "city": "South Columbus",
  "industry": "Investment/energy company",
  "group": "energy",
  "donorKey": "boich companies llc"
 },
 {
  "date": "2026-03-09",
  "amount": 5000.0,
  "name": "South Florida Stadium LLC (Miami Dolphins)",
  "city": "Miami Gardens",
  "industry": "Entertainment venue",
  "group": "hosp",
  "donorKey": "south florida stadium llc (miami dolphins)"
 },
 {
  "date": "2026-03-23",
  "amount": 5000.0,
  "name": "David Adler (Adler Development)",
  "city": "Pembroke Pines",
  "industry": "Developer",
  "group": "re",
  "donorKey": "david adler (adler development)"
 },
 {
  "date": "2026-03-24",
  "amount": 12000.0,
  "name": "LSN Law",
  "city": "Miami",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "lsn law"
 },
 {
  "date": "2026-03-27",
  "amount": 5000.0,
  "name": "Alan Annex (Greenberg Traurig)",
  "city": "Miami Beach",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "alan annex (greenberg traurig)"
 },
 {
  "date": "2026-03-28",
  "amount": 1000.0,
  "name": "Univista Properties Management",
  "city": "Miami",
  "industry": "Asset management",
  "group": "re",
  "donorKey": "univista properties management"
 },
 {
  "date": "2026-03-30",
  "amount": 25000.0,
  "name": "Michael D. Wohl (Coral Rock Development)",
  "city": "Coral Gables",
  "industry": "Real estate investor",
  "group": "re",
  "donorKey": "michael d wohl (coral rock development)"
 },
 {
  "date": "2026-03-30",
  "amount": 25000.0,
  "name": "Bluenest Development LLC",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "bluenest development llc"
 },
 {
  "date": "2026-03-30",
  "amount": 15000.0,
  "name": "13th Floor Manager, LLC",
  "city": "Miami",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "13th floor manager llc"
 },
 {
  "date": "2026-03-30",
  "amount": 10000.0,
  "name": "Fisher Island Community Association",
  "city": "Miami Beach",
  "industry": "Property management",
  "group": "re",
  "donorKey": "fisher island community association"
 },
 {
  "date": "2026-03-30",
  "amount": 5000.0,
  "name": "Independent Living Systems",
  "city": "Miami",
  "industry": "Assisted living facility",
  "group": "health",
  "donorKey": "independent living systems"
 },
 {
  "date": "2026-03-30",
  "amount": 5000.0,
  "name": "The Ferraro Law Firm, P.A.",
  "city": "Miami",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "the ferraro law firm p a"
 },
 {
  "date": "2026-03-30",
  "amount": 5000.0,
  "name": "Damian L. Gallo & Associates",
  "city": "Pinecrest",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "damian l gallo & associates"
 },
 {
  "date": "2026-03-30",
  "amount": 5000.0,
  "name": "Bilzin Sumberg Baena Price",
  "city": "Miami",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "bilzin sumberg baena price"
 },
 {
  "date": "2026-03-30",
  "amount": 3000.0,
  "name": "John Mangel",
  "city": "Winnetka",
  "industry": "Real estate investor",
  "group": "re",
  "donorKey": "john mangel"
 },
 {
  "date": "2026-03-30",
  "amount": 2500.0,
  "name": "Amkin Management LLC",
  "city": "Miami",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "amkin management llc"
 },
 {
  "date": "2026-03-30",
  "amount": 1000.0,
  "name": "Desarrollo Florida, LLC",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "desarrollo florida llc"
 },
 {
  "date": "2026-03-30",
  "amount": 500.0,
  "name": "Diaz Faquiry",
  "city": "Miami",
  "industry": "Real estate investor",
  "group": "re",
  "donorKey": "diaz faquiry"
 },
 {
  "date": "2026-03-31",
  "amount": 10000.0,
  "name": "Lemartec Corporation (Mastec)",
  "city": "Coconut Grove",
  "industry": "Construction",
  "group": "build",
  "donorKey": "lemartec corporation (mastec)"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "General Property Construction",
  "city": "Doral",
  "industry": "Construction",
  "group": "build",
  "donorKey": "general property construction"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Bertolotto Porte Inc.",
  "city": "Miami",
  "industry": "Door manufacturer",
  "group": "build",
  "donorKey": "bertolotto porte inc"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Maison Companies LLC",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "maison companies llc"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Laborcon, LLC (Coastal Construction)",
  "city": "Miami",
  "industry": "Construction",
  "group": "build",
  "donorKey": "laborcon llc (coastal construction)"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Wynwood Glass",
  "city": "North Miami",
  "industry": "Glass contractor",
  "group": "build",
  "donorKey": "wynwood glass"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "KD Construction Of Florida",
  "city": "Ft. Lauderdale",
  "industry": "Construction",
  "group": "build",
  "donorKey": "kd construction of florida"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Paramount Depot LLC",
  "city": "Doral",
  "industry": "Construction",
  "group": "build",
  "donorKey": "paramount depot llc"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Pacific Glass Corp.",
  "city": "Doral",
  "industry": "Commercial glass installer",
  "group": "build",
  "donorKey": "pacific glass corp"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "South Dade Lighting, Inc.",
  "city": "Miami",
  "industry": "Lighting company",
  "group": "build",
  "donorKey": "south dade lighting inc"
 },
 {
  "date": "2026-03-31",
  "amount": 2500.0,
  "name": "Therma Seal Insulation Systems",
  "city": "West Palm Beach",
  "industry": "Insulator",
  "group": "build",
  "donorKey": "therma seal insulation systems"
 },
 {
  "date": "2026-04-08",
  "amount": 1000.0,
  "name": "Thirteen Holdings LLC",
  "city": "Coral Gables",
  "industry": "Real estate holdings",
  "group": "re",
  "donorKey": "thirteen holdings llc"
 },
 {
  "date": "2026-04-09",
  "amount": 10000.0,
  "name": "Fisher Island Club, Inc.",
  "city": "Fisher Island",
  "industry": "Recreation/social club",
  "group": "hosp",
  "donorKey": "fisher island club inc"
 },
 {
  "date": "2026-04-09",
  "amount": 5000.0,
  "name": "Gaetano Bellavista Caltagiro",
  "city": "Coral Gables",
  "industry": "Real estate broker",
  "group": "re",
  "donorKey": "gaetano bellavista caltagiro"
 },
 {
  "date": "2026-04-13",
  "amount": 10000.0,
  "name": "Heather Capriola (Douglas Elliman)",
  "city": "New York",
  "industry": "Real estate finance",
  "group": "re",
  "donorKey": "heather capriola (douglas elliman)"
 },
 {
  "date": "2026-04-15",
  "amount": 10000.0,
  "name": "Nextera Energy Capital Holding (FPL parent company)",
  "city": "Juno Beach",
  "industry": "Energy company",
  "group": "energy",
  "donorKey": "nextera energy capital holding (fpl parent company)"
 },
 {
  "date": "2026-04-15",
  "amount": 2500.0,
  "name": "Integrated Openings Solutions",
  "city": "Olathe",
  "industry": "Construction company",
  "group": "build",
  "donorKey": "integrated openings solutions"
 },
 {
  "date": "2026-04-20",
  "amount": 15000.0,
  "name": "1672 Calle Ocho LLC (Hector Ortiz)",
  "city": "Hialeah",
  "industry": "Commercial real estate",
  "group": "re",
  "donorKey": "1672 calle ocho llc (hector ortiz)"
 },
 {
  "date": "2026-04-20",
  "amount": 5000.0,
  "name": "Edgewater Management Services",
  "city": "Miami",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "edgewater management services"
 },
 {
  "date": "2026-04-20",
  "amount": 5000.0,
  "name": "AUM Construction, Inc.",
  "city": "Hialeah Gardens",
  "industry": "Construction",
  "group": "build",
  "donorKey": "aum construction inc"
 },
 {
  "date": "2026-04-22",
  "amount": 5000.0,
  "name": "Alan T. Dimond (Greenberg Traurig)",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "alan t dimond (greenberg traurig)"
 },
 {
  "date": "2026-04-22",
  "amount": 5000.0,
  "name": "TWJ Office LLC",
  "city": "Miami",
  "industry": "Property management",
  "group": "re",
  "donorKey": "twj office llc"
 },
 {
  "date": "2026-04-22",
  "amount": 2500.0,
  "name": "A+ Mini Storage South Miami",
  "city": "Miami",
  "industry": "Storage",
  "group": "storage",
  "donorKey": "a+ mini storage south miami"
 },
 {
  "date": "2026-04-22",
  "amount": 2500.0,
  "name": "A+ Mini Storage Kendall",
  "city": "Miami",
  "industry": "Storage",
  "group": "storage",
  "donorKey": "a+ mini storage kendall"
 },
 {
  "date": "2026-04-22",
  "amount": 2500.0,
  "name": "A+ Mini Storage West Kendall",
  "city": "Miami",
  "industry": "Storage",
  "group": "storage",
  "donorKey": "a+ mini storage west kendall"
 },
 {
  "date": "2026-04-22",
  "amount": 2500.0,
  "name": "Robert Behar",
  "city": "Coral Gables",
  "industry": "Architect",
  "group": "build",
  "donorKey": "robert behar"
 },
 {
  "date": "2026-04-22",
  "amount": 2500.0,
  "name": "A+ Mini Storage Business Center",
  "city": "Miami",
  "industry": "Storage",
  "group": "storage",
  "donorKey": "a+ mini storage business center"
 },
 {
  "date": "2026-04-22",
  "amount": 1350.0,
  "name": "River Rapids Partners II, LLC (Rovr)",
  "city": "Coral Gables",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "river rapids partners ii llc (rovr)"
 },
 {
  "date": "2026-04-22",
  "amount": 1350.0,
  "name": "Delaware Parkway Partners, LLC",
  "city": "Coral Gables",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "delaware parkway partners llc"
 },
 {
  "date": "2026-04-22",
  "amount": 1300.0,
  "name": "Rovr Development LLC",
  "city": "Coral Gables",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "rovr development llc"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Jorge Navarro (Greenberg Traurig)",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "jorge navarro (greenberg traurig)"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Brian Dombrowski (Greenberg Traurig)",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "brian dombrowski (greenberg traurig)"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Jay Massirman",
  "city": "Miami",
  "industry": "Real estate broker",
  "group": "re",
  "donorKey": "jay massirman"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Anillo Toledo Lopez, LLC",
  "city": "Miami",
  "industry": "Construction",
  "group": "build",
  "donorKey": "anillo toledo lopez llc"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Alberto Cordoves",
  "city": "Coral Gables",
  "industry": "Architect",
  "group": "build",
  "donorKey": "alberto cordoves"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Carlos L. Diaz Sotolongo",
  "city": "Miami Lakes",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "carlos l diaz sotolongo"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Iris V. Escarra (Greenberg Traurig)",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "iris v escarra (greenberg traurig)"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Kerri Lew Barsh (Greenberg Traurig)",
  "city": "Miami Beach",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "kerri lew barsh (greenberg traurig)"
 },
 {
  "date": "2026-04-22",
  "amount": 1000.0,
  "name": "Global Investments Realty Inc.",
  "city": "Miami",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "global investments realty inc"
 },
 {
  "date": "2026-04-22",
  "amount": 500.0,
  "name": "Nicole S. Wolfe (Greenberg Traurig)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "nicole s wolfe (greenberg traurig)"
 },
 {
  "date": "2026-04-22",
  "amount": 500.0,
  "name": "Alfredo J. Gonzalez (Greenberg Traurig)",
  "city": "Miami Beach",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "alfredo j gonzalez (greenberg traurig)"
 },
 {
  "date": "2026-04-24",
  "amount": 10000.0,
  "name": "New Arena Square North & South",
  "city": "Miami",
  "industry": "Apartment complex",
  "group": "re",
  "donorKey": "new arena square north & south"
 },
 {
  "date": "2026-04-27",
  "amount": 10000.0,
  "name": "SG Manager. LLC (Michael Swerdlow)",
  "city": "Coconut Grove",
  "industry": "Property management",
  "group": "re",
  "donorKey": "sg manager llc (michael swerdlow)"
 },
 {
  "date": "2026-04-27",
  "amount": 10000.0,
  "name": "Golden Property Management",
  "city": "Miami",
  "industry": "Property management",
  "group": "re",
  "donorKey": "golden property management"
 },
 {
  "date": "2026-04-27",
  "amount": 5000.0,
  "name": "Scott Srebnick (Goldman Properties)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "scott srebnick (goldman properties)"
 },
 {
  "date": "2026-04-28",
  "amount": 2000.0,
  "name": "8038 and 165 Owner LLC (Infinity Real Estate and Infinity Collective)",
  "city": "New York",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "8038 and 165 owner llc (infinity real estate and infinity collective)"
 },
 {
  "date": "2026-04-30",
  "amount": 10000.0,
  "name": "Alex Solovey",
  "city": "Englewood Cliffs",
  "industry": "Nursing homes",
  "group": "health",
  "donorKey": "alex solovey"
 },
 {
  "date": "2026-04-30",
  "amount": 5000.0,
  "name": "Space Invaders, LLC (Factory Town operators)",
  "city": "Miami",
  "industry": "Hospitality",
  "group": "hosp",
  "donorKey": "space invaders llc (factory town operators)"
 },
 {
  "date": "2026-04-30",
  "amount": 2000.0,
  "name": "Terra City Center MF LLC (Terra)",
  "city": "Coconut Grove",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "terra city center mf llc (terra)"
 },
 {
  "date": "2026-04-30",
  "amount": 1500.0,
  "name": "CSP MF Communities I, LLC (Terra)",
  "city": "Coconut Grove",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "csp mf communities i llc (terra)"
 },
 {
  "date": "2026-04-30",
  "amount": 1500.0,
  "name": "Lakeview Hospitality Investments (Terra)",
  "city": "Coconut Grove",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "lakeview hospitality investments (terra)"
 },
 {
  "date": "2026-05-04",
  "amount": 10000.0,
  "name": "TMC Naranja 66 Holdings LLC",
  "city": "Miami Lakes",
  "industry": "Real estate holdings",
  "group": "re",
  "donorKey": "tmc naranja 66 holdings llc"
 },
 {
  "date": "2026-05-05",
  "amount": 5000.0,
  "name": "Mana Miami Management, LLC",
  "city": "Miami",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "mana miami management llc"
 },
 {
  "date": "2026-05-10",
  "amount": 25000.0,
  "name": "Christopher Torto",
  "city": "Miami Beach",
  "industry": "Data centers",
  "group": "dc",
  "donorKey": "christopher torto"
 },
 {
  "date": "2026-05-27",
  "amount": 5000.0,
  "name": "Florida East Coast Railway, LLC",
  "city": "Jacksonville",
  "industry": "Transportation",
  "group": "transport",
  "donorKey": "florida east coast railway llc"
 },
 {
  "date": "2026-05-28",
  "amount": 10000.0,
  "name": "SG Manager. LLC (Michael Swerdlow)",
  "city": "Coconut Grove",
  "industry": "Property management",
  "group": "re",
  "donorKey": "sg manager llc (michael swerdlow)"
 },
 {
  "date": "2026-05-29",
  "amount": 10000.0,
  "name": "Housing Trust Group, LLC",
  "city": "Coconut Grove",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "housing trust group llc"
 },
 {
  "date": "2026-05-29",
  "amount": 10000.0,
  "name": "Arturo Vidal (North Development)",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "arturo vidal (north development)"
 },
 {
  "date": "2026-05-29",
  "amount": 3000.0,
  "name": "Javier E. Fernandez Esq PA",
  "city": "Coral Gables",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "javier e fernandez esq pa"
 },
 {
  "date": "2026-06-12",
  "amount": 25000.0,
  "name": "Michael D. Wohl (Coral Rock Development)",
  "city": "Coral Gables",
  "industry": "Real estate investor",
  "group": "re",
  "donorKey": "michael d wohl (coral rock development)"
 },
 {
  "date": "2026-06-19",
  "amount": 2500.0,
  "name": "Khanna Family Holdings LLC",
  "city": "Miami",
  "industry": "Real estate holdings",
  "group": "re",
  "donorKey": "khanna family holdings llc"
 },
 {
  "date": "2026-06-24",
  "amount": 10000.0,
  "name": "Jay Roberts (Prosper Group)",
  "city": "Miami",
  "industry": "Real estate investor",
  "group": "re",
  "donorKey": "jay roberts (prosper group)"
 },
 {
  "date": "2026-06-24",
  "amount": 2500.0,
  "name": "Miccosukee Tribe",
  "city": "Miccosukee Tribe",
  "industry": "Native American tribe",
  "group": "misc",
  "donorKey": "miccosukee tribe"
 },
 {
  "date": "2026-06-26",
  "amount": 5000.0,
  "name": "Lore Development Group LLC",
  "city": "Miami",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "lore development group llc"
 },
 {
  "date": "2026-06-29",
  "amount": 10000.0,
  "name": "Ric-Man International, Inc.",
  "city": "Pompano Beach",
  "industry": "Construction",
  "group": "build",
  "donorKey": "ric-man international inc"
 },
 {
  "date": "2026-06-29",
  "amount": 1000.0,
  "name": "Pedro Gassant (Holland & Knight)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "pedro gassant (holland & knight)"
 },
 {
  "date": "2026-06-29",
  "amount": 200.0,
  "name": "Alessandria San Roman (Holland & Knight)",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "alessandria san roman (holland & knight)"
 },
 {
  "date": "2026-06-30",
  "amount": 1000.0,
  "name": "Hugo Arza (Holland & Knight)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "hugo arza (holland & knight)"
 },
 {
  "date": "2026-07-01",
  "amount": 2000.0,
  "name": "Brightline Trains Florida LLC",
  "city": "Miami",
  "industry": "Transportation",
  "group": "transport",
  "donorKey": "brightline trains florida llc"
 },
 {
  "date": "2026-07-01",
  "amount": 250.0,
  "name": "Miriam Soler Ramos (Holland & Knight)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "miriam soler ramos (holland & knight)"
 },
 {
  "date": "2026-07-08",
  "amount": 300.0,
  "name": "Vanessa Madrid (Holland & Knight)",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "vanessa madrid (holland & knight)"
 },
 {
  "date": "2026-07-09",
  "amount": 500.0,
  "name": "Alejandro Arias (Holland & Knight)",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "alejandro arias (holland & knight)"
 },
 {
  "date": "2026-07-17",
  "amount": 10000.0,
  "name": "Baker Barrios",
  "city": "Orlando",
  "industry": "Architect firm",
  "group": "build",
  "donorKey": "baker barrios"
 },
 {
  "date": "2026-07-17",
  "amount": 10000.0,
  "name": "Bercow Radell Fernandez Larkin",
  "city": "Miami",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "bercow radell fernandez larkin"
 },
 {
  "date": "2026-07-17",
  "amount": 5000.0,
  "name": "100 Biscayne LLC (RFR)",
  "city": "Stamford",
  "industry": "Commercial real estate",
  "group": "re",
  "donorKey": "100 biscayne llc (rfr)"
 },
 {
  "date": "2026-07-17",
  "amount": 5000.0,
  "name": "Norwegian Wood Acquisitions LLC",
  "city": "Miami",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "norwegian wood acquisitions llc"
 },
 {
  "date": "2026-07-17",
  "amount": 2500.0,
  "name": "Interurban, LLC",
  "city": "Miami",
  "industry": "Real estate investment",
  "group": "re",
  "donorKey": "interurban llc"
 },
 {
  "date": "2026-07-17",
  "amount": 1000.0,
  "name": "Birddog Development Partners",
  "city": "Orlando",
  "industry": "Real estate development",
  "group": "re",
  "donorKey": "birddog development partners"
 },
 {
  "date": "2026-07-20",
  "amount": 10000.0,
  "name": "SG Manager, LLC (Michael Swerdlow)",
  "city": "Coconut Grove",
  "industry": "Property management",
  "group": "re",
  "donorKey": "sg manager llc (michael swerdlow)"
 },
 {
  "date": "2026-07-23",
  "amount": 3000.0,
  "name": "Chris Korge",
  "city": "Miami",
  "industry": "Developer",
  "group": "re",
  "donorKey": "chris korge"
 },
 {
  "date": "2026-07-28",
  "amount": 10000.0,
  "name": "Terra City Center Mf LLC (Terra)",
  "city": "Coconut Grove",
  "industry": "Real estate management",
  "group": "re",
  "donorKey": "terra city center mf llc (terra)"
 },
 {
  "date": "2026-07-28",
  "amount": 10000.0,
  "name": "Crei Holdings LLC",
  "city": "Miami",
  "industry": "Real estate holdings",
  "group": "re",
  "donorKey": "crei holdings llc"
 },
 {
  "date": "2026-07-29",
  "amount": 5000.0,
  "name": "Javier E. Fernandez Esq PA",
  "city": "Coral Gables",
  "industry": "Law firm",
  "group": "law",
  "donorKey": "javier e fernandez esq pa"
 },
 {
  "date": "2026-07-30",
  "amount": 5000.0,
  "name": "Weiss Serota Helfman Cole & Bierman",
  "city": "Coral Gables",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "weiss serota helfman cole & bierman"
 },
 {
  "date": "2026-07-30",
  "amount": 500.0,
  "name": "Alejandro Uriba",
  "city": "Miami",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "alejandro uriba"
 },
 {
  "date": "2026-07-30",
  "amount": 250.0,
  "name": "Edward O. Martos",
  "city": "Pinecrest",
  "industry": "Attorney",
  "group": "law",
  "donorKey": "edward o martos"
 }
];
