name: Midtown South Rezoning Map Update

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  update-midtown-south:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # System packages needed by GeoPandas/Fiona (KML via GDAL/PROJ)
      - name: Install system libs (GDAL/PROJ/GEOS)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gdal-bin libgdal-dev \
            libspatialindex-dev \
            proj-bin proj-data

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./midtown_south_rezoning_08_28_25/requirements.txt
          # Ensure notebook execution tool is present
          pip install jupyter nbconvert

      - name: Write Google service account JSON
        run: |
          echo "${{ secrets.AUTO_SCRAPER_CREDENTIALS_BASE64 }}" | base64 --decode > ./midtown_south_rezoning_08_28_25/autoscraper-380600-0d0c84856d6b.json

      - name: Execute notebook → produce index.html
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute ./midtown_south_rezoning_08_28_25/midtown_south_rezoning.ipynb \
            --output ./midtown_south_rezoning_08_28_25/executed.ipynb \
            --ExecutePreprocessor.timeout=-1

          # Sanity check: ensure index.html exists where your site expects it
          test -f ./midtown_south_rezoning_08_28_25/index.html || (echo "index.html not found; check notebook save path" && exit 1)

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./midtown_south_rezoning_08_28_25/index.html ./midtown_south_rezoning_08_28_25/executed.ipynb || true
          git commit -m "Update Midtown South Rezoning map" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Clean up (always)
        if: always()
        run: |
          rm -f ./midtown_south_rezoning_08_28_25/autoscraper-380600-0d0c84856d6b.json
